"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, use environment variable: SECRET_KEY = os.environ.get('SECRET_KEY')
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-aa@ka2@_t!h=d_2-z6o3%j@1=+ioel3c+m&84rrl+v_e&_it89')

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG=False in production. Use environment variable for production deployment.
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

# ALLOWED_HOSTS: List of host/domain names this site can serve.
# In production, set this to your actual domain names.
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom security middleware for Content Security Policy headers
    'bookshelf.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploaded files)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# Authentication settings
LOGIN_URL = 'relationship_app:login'
LOGIN_REDIRECT_URL = 'relationship_app:list_books'
LOGOUT_REDIRECT_URL = 'relationship_app:logout'


# =============================================================================
# SECURITY SETTINGS
# =============================================================================

# SECURE_BROWSER_XSS_FILTER: Enables browser's XSS filtering protection
# This adds X-XSS-Protection header to help protect against XSS attacks
SECURE_BROWSER_XSS_FILTER = True

# X_FRAME_OPTIONS: Controls whether site can be displayed in a frame
# Set to 'DENY' to prevent clickjacking attacks by blocking any domain from framing the page
X_FRAME_OPTIONS = 'DENY'

# SECURE_CONTENT_TYPE_NOSNIFF: Prevents browsers from MIME-sniffing response content types
# Protects against MIME type sniffing vulnerabilities
SECURE_CONTENT_TYPE_NOSNIFF = True

# CSRF_COOKIE_SECURE: Ensures CSRF cookie is only sent over HTTPS connections
# When True, the CSRF cookie will only be sent over HTTPS, preventing interception over HTTP
# This protects the CSRF token from being stolen via man-in-the-middle attacks
# Set to True in production when using HTTPS
# IMPORTANT: Set to True only when HTTPS is properly configured, otherwise CSRF will fail
# Without HTTPS, users will not be able to submit forms
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False').lower() == 'true'

# SESSION_COOKIE_SECURE: Ensures session cookie is only sent over HTTPS connections
# When True, the session cookie will only be sent over HTTPS connections
# This prevents session hijacking attacks where cookies are intercepted over unencrypted connections
# Set to True in production when using HTTPS
# IMPORTANT: Set to True only when HTTPS is properly configured, otherwise sessions will fail
# Without HTTPS, users will not be able to maintain login sessions
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False').lower() == 'true'

# CSRF_COOKIE_HTTPONLY: Prevents JavaScript from accessing CSRF cookie (not supported by all browsers)
# Additional protection against XSS attacks trying to steal CSRF token
CSRF_COOKIE_HTTPONLY = False  # Django doesn't support this natively, but good practice if middleware added

# SESSION_COOKIE_HTTPONLY: Prevents JavaScript from accessing session cookie
# Protects session cookies from being accessed via JavaScript (XSS protection)
SESSION_COOKIE_HTTPONLY = True

# SESSION_COOKIE_SAMESITE: Helps protect against CSRF attacks
# 'Strict' provides the strongest protection but may affect some user flows
SESSION_COOKIE_SAMESITE = 'Lax'

# SECURE_SSL_REDIRECT: Redirects all HTTP requests to HTTPS
# Enable only in production with proper SSL certificate
# This ensures all HTTP requests are automatically redirected to HTTPS
# IMPORTANT: Only set to True when SSL certificate is properly configured
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() == 'true'

# HTTP Strict Transport Security (HSTS) Settings
# HSTS instructs browsers to only access the site via HTTPS for a specified period

# SECURE_HSTS_SECONDS: The number of seconds the HSTS policy should remain in effect
# 31536000 seconds = 1 year
# This tells browsers to only access the site via HTTPS for the next year
# IMPORTANT: Only enable in production after thoroughly testing HTTPS setup
# Once enabled and deployed, browsers will cache this policy for the specified duration
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))

# SECURE_HSTS_INCLUDE_SUBDOMAINS: Include all subdomains in the HSTS policy
# When True, HSTS policy applies to all subdomains of the current domain
# Example: If set for example.com, it also applies to www.example.com, api.example.com, etc.
# IMPORTANT: Only enable if all subdomains support HTTPS properly
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False').lower() == 'true'

# SECURE_HSTS_PRELOAD: Allow the site to be included in browser HSTS preload lists
# When True, the site can be submitted to browser HSTS preload lists (e.g., hstspreload.org)
# Preloading ensures browsers always use HTTPS even before the first visit
# IMPORTANT: Only enable if you've committed to long-term HTTPS support
# Once added to preload lists, it's difficult to remove
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'False').lower() == 'true'

# Content Security Policy (CSP) Settings
# CSP helps prevent XSS attacks by specifying which domains are allowed to load resources
# This is a basic CSP - adjust based on your application's needs
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'")  # 'unsafe-inline' needed for Django admin, but should be restricted
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")  # 'unsafe-inline' needed for Django admin
CSP_IMG_SRC = ("'self'", "data:",)
CSP_FONT_SRC = ("'self'",)

# Note: For production, consider using django-csp package for more advanced CSP configuration
# Or set CSP headers via middleware manually
